### ISSUE TITLE
Mute or log the Python stack traces

### ISSUE THREAD

**Issue by majensen** [LabAdvComp/parcel#65]
When Python exceptions are hit, the screen fills with very long stack traces. Users are likely to be terrified. Can these be muted, added back with a --verbose switch?

**Comment by majensen** [comment]
Example snip: after hitting ctrl-c to escape a stuck download:
```
2015-08-01 21:59:41,219: INFO: Downloading file to : /Users/jensenma/Code/GDC/parcel/goob/433ce336-a590-42ae-810e-6abe10c123a5_nationwidechildrens.org_biospecimen.TCGA-2F-A9KT.xml
^CProcess Process-20:a590-42ae-810e-6abe10c123a5:  74% [#######################        ] ETA:  0:00:00 106.82 kB/s 
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
KeyboardInterrupt
2015-08-01 21:59:56,862: ERROR: Unable to download 433ce336-a590-42ae-810e-6abe10c123a5: 
2015-08-01 21:59:56,863: INFO: ^------ 433ce336-a590-42ae-810e-6abe10c123a5 ------^
2015-08-01 21:59:56,863: INFO: 
2015-08-01 21:59:56,863: INFO: v------ dd7d5059-e6fb-4dc1-818d-33197e84e9f6 ------v
Process Process-24:
Process Process-27:
Process Process-22:
Process Process-23:
Process Process-21:
Process Process-25:
Process Process-26:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py",  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
 line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 32, in download_worker
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 32, in download_worker
    self.run()
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
    client.read_write_segment(path, file_id, interval, producer.q_complete)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 215, in read_write_segment
    r = self.make_file_request(file_id, headers)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 117, in make_file_request
    r = s.get(url, headers=headers, verify=verify, stream=True)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 473, in get
    client.read_write_segment(path, file_id, interval, producer.q_complete)
    self.run()
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 215, in read_write_segment
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    r = self.make_file_request(file_id, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 117, in make_file_request
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
    self._target(*self._args, **self._kwargs)
  File "/Users/jensenma/Code/GDC/parcel/parcel/client.py", line 29, in download_worker
    r = s.get(url, headers=headers, verify=verify, stream=True)
    interval = producer.q_work.get()
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 473, in get
  File "<string>", line 2, in get
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    interval = producer.q_work.get()
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "<string>", line 2, in get
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
    kind, result = conn.recv()
KeyboardInterrupt
KeyboardInterrupt
    kind, result = conn.recv()
KeyboardInterrupt
    kind, result = conn.recv()
KeyboardInterrupt
    kind, result = conn.recv()
KeyboardInterrupt
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/adapters.py", line 370, in send
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
  File "/Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    httplib_response = conn.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    line = self.fp.readline(_MAXLINE + 1)
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 241, in recv
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 160, in read
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
    return self._sslobj.read(len)
KeyboardInterrupt
KeyboardInterrupt
2015-08-01 21:59:57,684: INFO: Request responded: 63382 bytes
2015-08-01 21:59:57,684: INFO: Starting download   : dd7d5059-e6fb-4dc1-818d-33197e84e9f6
2015-08-01 21:59:57,684: INFO: File name           : nationwidechildrens.org_biospecimen.TCGA-2F-A9KR.xml
2015-08-01 21:59:57,684: INFO: Download size       : 63382 B (0.00 GB)
2015-08-01 21:59:57,685: INFO: Downloading file to : /Users/jensenma/Code/GDC/parcel/goob/dd7d5059-e6fb-4dc1-818d-33197e84e9f6_nationwidechildrens.org_biospecimen.TCGA-2F-A9KR.xml
Downloading dd7d5059-e6fb-4dc1-818d-33197e84e9f6:  74% [#######################        ] ETA:  0:00:00  82.10 kB/
```

**Comment by millerjs** [comment]
Excessive tracebacks are well known with python's multiprocessing module. I agree that this is intimidating/annoying to the user and will look into silencing it.
